const THEMES = {
  bodeguita: {
    "--color-primary": "#0D332F",
    "--color-on-primary": "#FFFFFF",
    "--color-primary-container": "#D4E8D1",
    "--color-on-primary-container": "#0D332F",
    "--color-secondary": "#C8A84E",
    "--color-on-secondary": "#FFFFFF",
    "--color-secondary-container": "#F5EFD5",
    "--color-on-secondary-container": "#3A2E0F",
    "--color-tertiary": "#C97B5A",
    "--color-on-tertiary": "#FFFFFF",
    "--color-tertiary-container": "#FBE9E0",
    "--color-on-tertiary-container": "#5A2A1A",
    "--color-error": "#BA1A1A",
    "--color-on-error": "#FFFFFF",
    "--color-error-container": "#FFDAD6",
    "--color-on-error-container": "#93000A",
    "--color-background": "#FCFAF5",
    "--color-on-background": "#1B1C1A",
    "--color-surface": "#F8F5EE",
    "--color-on-surface": "#1B1C1A",
    "--color-surface-dim": "#D5D1CA",
    "--color-surface-bright": "#FCFAF5",
    "--color-surface-container-lowest": "#FFFFFF",
    "--color-surface-container-low": "#F4F0EA",
    "--color-surface-container": "#EDEAE3",
    "--color-surface-container-high": "#E8E4DC",
    "--color-surface-container-highest": "#E2DED6",
    "--color-on-surface-variant": "#49454F",
    "--color-outline": "#7A767F",
    "--color-outline-variant": "#CAC6CF",
    "--color-inverse-surface": "#30312E",
    "--color-inverse-on-surface": "#F2F0ED",
    "--color-inverse-primary": "#9ED1BD",
    "--color-surface-tint": "#0D332F",
    "--color-warning": "#C8A84E",
    "--color-on-warning": "#1A1A1A",
    "--primary-blue": "#0D332F",
    "--primary-blue-dark": "#091F1C",
    "--primary-blue-light": "#E8F5E9",
    "--primary-green": "#0D332F",
    "--primary-green-dark": "#091F1C",
    "--primary-green-light": "#E8F5E9",
    "--accent-teal": "#C8A84E",
    "--accent-teal-light": "#F5EFD5",
    "--success": "#0D332F",
    "--success-light": "#E8F5E9",
    "--warning-old": "#C8A84E",
    "--warning-light": "#FFF8E1",
    "--error": "#BA1A1A",
    "--error-light": "#FFDAD6",
  },
  blue: {
    "--color-primary": "#1B4965",
    "--color-on-primary": "#FFFFFF",
    "--color-primary-container": "#D1E4F0",
    "--color-on-primary-container": "#001F33",
    "--color-secondary": "#62B6CB",
    "--color-on-secondary": "#001F2A",
    "--color-secondary-container": "#C5E8F2",
    "--color-on-secondary-container": "#001F2A",
    "--color-background": "#F5F8FA",
    "--color-on-background": "#1B1C1A",
    "--color-surface": "#FFFFFF",
    "--color-on-surface": "#1B1C1A",
    "--color-error": "#BA1A1A",
    "--color-on-error": "#FFFFFF",
  },
  green: {
    "--color-primary": "#2D6A4F",
    "--color-on-primary": "#FFFFFF",
    "--color-primary-container": "#C8E6C9",
    "--color-on-primary-container": "#002117",
    "--color-secondary": "#40916C",
    "--color-on-secondary": "#FFFFFF",
    "--color-secondary-container": "#D1FAE5",
    "--color-on-secondary-container": "#002117",
    "--color-background": "#F0F7F4",
    "--color-on-background": "#1B1C1A",
    "--color-surface": "#FFFFFF",
    "--color-on-surface": "#1B1C1A",
  },
  sky: {
    "--color-primary": "#0284C7",
    "--color-on-primary": "#FFFFFF",
    "--color-primary-container": "#BAE6FD",
    "--color-on-primary-container": "#00324F",
    "--color-secondary": "#0EA5E9",
    "--color-on-secondary": "#FFFFFF",
    "--color-secondary-container": "#E0F2FE",
    "--color-on-secondary-container": "#00324F",
    "--color-background": "#F0F9FF",
    "--color-on-background": "#1B1C1A",
    "--color-surface": "#FFFFFF",
    "--color-on-surface": "#1B1C1A",
  },
};

export const getThemePreview = (themeName) => {
  return THEMES[themeName] || THEMES.bodeguita;
};

export const applyTheme = (themeName) => {
  const theme = getThemePreview(themeName);
  const root = document.documentElement;

  Object.entries(theme).forEach(([property, value]) => {
    root.style.setProperty(property, value);
  });
};
